test_absolute (__main__.TestExercice) ... ok
test_factorial (__main__.TestExercice) ... ok
test_prefixes (__main__.TestExercice) ... ok
test_summation (__main__.TestExercice) ... FAIL
test_verify_ages (__main__.TestExercice) ... ok

======================================================================
FAIL: test_summation (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\zevic\OneDrive\Documents\Université\Session A2021\INF1007\Programmes\c03_ch5_exercices-VictorGilbert\test_exercice.py", line 47, in test_summation
    self.assertEqual(
AssertionError: 10001 != 24133 : Mauvaise réponse

----------------------------------------------------------------------
Ran 5 tests in 0.025s

FAILED (failures=1)
